### ISSUE TITLE
[$40] [Create resource] 404 code returns while creating a new resource

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/resources-api#16]
**Steps to reproduce:** 
  - run `challenge-api` service in local
  - run the app by: `PORT=3003 CHALLENGE_API_URL=http://localhost:3000/v5/challenges npm start`
  - open the Postman collection
  - send requests to create ResourceRoles, ResourceRolePhaseDependencies if it is the first time
  - send the request `create resource by admin`

**Current result(s):**  
 - the request returns 404 (Not Found) code

**Expected result(s):**  
 - should be 400 (Bad Request) for the challengeId not existed case

**Attachments:**  
![Untitled](https://user-images.githubusercontent.com/36178659/77815533-75da7580-70ee-11ea-9fcf-057b5d9be8e3.png)

**Comment by nqviet** [comment]
also happen with `get resources`

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30121642 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors this is open for pickup. Please create a PR against the `develop` branch.

**Comment by cunhavictor** [comment]
Thomas, anyone can take this?

**Comment by ThomasKranitsas** [comment]
Yes, if you have registered with Topcoder-X before, you can take it

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30121642 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by rashmi73** [comment]
@ThomasKranitsas PR in few hours

**Comment by ThomasKranitsas** [comment]
@rashmi73 can I get an update please?

**Comment by rashmi73** [comment]
@ThomasKranitsas yes near to complete it

**Comment by ThomasKranitsas** [comment]
Ok, sounds good

**Comment by rashmi73** [comment]
@ThomasKranitsas suddenly create ResourceRolePhaseDependencies  is giving internal server error.

steps taken by me to run it locally.

1. cd local, run docker-compose up
2. npm run create-tables
3. in mock-challenge-api.js, at line 60 port changed to 3000.
4. PORT=3003 CHALLENGE_API_URL=http://localhost:3000/v5/challenges npm start
5. create resourceRole is successful via postman
and now

6. create ResourceRolePhaseDependencies giving message internal server error suddenly.

anything missed?

**Comment by ThomasKranitsas** [comment]
Can you please attach the error that's printed on the terminal so I can debug?

**Comment by rashmi73** [comment]
> set PORT=3003 && set CHALLENGE_API_URL=http://localhost:3000/v5/challenges && node app.js

info: Express server listening on port 3003
debug: ENTER createDependency
debug: input arguments
debug: { data:
   { phaseId: 'aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b',
     resourceRoleId: '5182af59-f91f-4466-a909-1c77f2c8c436',
     phaseState: false } }
error: Error happened in createDependency
error: Error: Unknown Error
    at Request._callback (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\tc-core-library-js\lib\auth\m2m.js:70:24)
    at Request.self.callback (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error: Error: Unknown Error
    at Request._callback (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\tc-core-library-js\lib\auth\m2m.js:70:24)
    at Request.self.callback (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error: Error happened in ResourceRolePhaseDependencyController#createDependency
error: { Error: Unknown Error
    at Request._callback (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\tc-core-library-js\lib\auth\m2m.js:70:24)
    at Request.self.callback (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (C:\Users\fdp2645\demoprojects\r\resources-api\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:6

**Comment by rashmi73** [comment]
@ThomasKranitsas related to m2m, AUTH0?

**Comment by rashmi73** [comment]
@ThomasKranitsas ok i found it, I need all Auth parameters to be set. messaging you on slack for env variables

**Comment by rashmi73** [comment]
@ThomasKranitsas @nqviet can you please elaborate more what is exactly required because issue description nowhere matches the results mentioned.


Description mentions: 
Current result is 404.

whereas on executing, it does not return 404, but 400 with message "Phase aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b should not be open"

surely something is wrong with issue description i feel.

Kindly correct me if I am misunderstanding.

**Comment by ThomasKranitsas** [comment]
@rashmi73  Closing this as discussed over Slack

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30121642<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```
